---
- name: Ensure all Docker containers are running
  hosts: docker
  become: true
  
  tasks:
    - name: Get all containers
      shell: docker ps -aq
      register: containers
      changed_when: false

    - name: Start all containers
      command: docker start {{ item }}
      loop: "{{ containers.stdout_lines }}"
      register: start_result
      failed_when: false
